### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by CrazyBunQnQ** [tenbot/tenbot#1]
## Environment

- Version: 最新
- OS: Macbook Pro
- Node Version: v13.8.0
- NPM Version: 6.13.4
- Yarn Version: 1.22

## 无法安装

![image](https://user-images.githubusercontent.com/17765748/75618954-17ce7700-5bb0-11ea-8587-c3ad1e8f01c1.png)

并且无法打开您的[项目文档](https://tenbot.github.io/)

该文档项目也是空的...

**Comment by meteorlxy** [comment]
还没正式发布呢，居然已经有人发现了 😅

**Comment by CrazyBunQnQ** [comment]
哈哈哈 期待啊

**Comment by meteorlxy** [comment]
突然就有发布的动力了 😄 我今天发个 prerelease 版

**Comment by CrazyBunQnQ** [comment]
这么给力！

**Comment by meteorlxy** [comment]
已发布，欢迎试用提建议 :smile:
