### ISSUE TITLE
接收请求时报错

### ISSUE THREAD

**Issue by CrazyBunQnQ** [tenbot/tenbot#2]
## Environment

OS: Macbook Pro
Node Version: v13.8.0
NPM Version: 6.13.4
Yarn Version: 1.22

## 接收请求时报错

![image](https://user-images.githubusercontent.com/17765748/75632608-c1f1e180-5c38-11ea-8350-1650fb61fb73.png)

## 关于配置

程序里有四个参数需要我设置，这四个参数，我不知道我理解的对不对

![image](https://user-images.githubusercontent.com/17765748/75639341-4fe6c000-5c6b-11ea-9fa9-1f2b0f973f55.png)

其中三个参数，需要先在企业微信里创建一个应用，开启 `API接收消息`，另一个参数是**从群聊里创建的群机器人**配置中获取

- 企业微信 `API 接收消息` 的 URL:  与 `app.ts` 一致，填 `http://${host}:${port}/bot`
- `bot.ts` 的 `token`: 将企业微信`API接收消息` 生成的 `Token` 填入
- `bot.ts` 的 `encodingAesKey`: 将企业微信`API接收消息` 生成的 `EncodingAESKey` 填入
- `bot.ts` 的 `webhook`: 将企业微信`群机器人` 的 ` Webhook 地址` 填入

是这样吗？

## 关于使用

然后使用方法我也不是特明白，也就是我现在创建了两个东西

- 开启了 `API接收消息` 的企业应用
- 群聊里的 `群机器人`

我是要私聊跟企业应用说话，然后`群机器人`会发消息给群里吗？
还是在群里 `@群机器人`，然后`群机器人`会做响应的消息回复呢？

**Comment by meteorlxy** [comment]
具体是发了什么消息？

**Comment by CrazyBunQnQ** [comment]
中文哈哈，或者纯英文字母
- 哈喽
- 啊
- dgg

**Comment by meteorlxy** [comment]
> 其中三个参数，需要先在企业微信里创建一个应用，开启 API接收消息，另一个参数是从群聊里创建的群机器人配置中获取

不需要创建应用，和企业应用完全无关，全部从群机器人获取。

不过我刚注意到，群机器人这部分好像还处于内测，鹅厂内部是可以用的，外部公司可能还用不了 😅

**Comment by CrazyBunQnQ** [comment]
尴尬...我说找了半天没找到那三个参数...好吧，那只能期待正式上线了...
