### ISSUE TITLE
[Bug Report] 企业微信机器人， 接收信息配置， 这个配置项是存在的？

### ISSUE THREAD

**Issue by zhongzi** [tenbot/tenbot#4]
## Environment

- Version:
- OS:
- Node Version:
- NPM Version:
- Yarn Version:

## Steps To Reproduce

1.

2.

3.

**Comment by zhongzi** [comment]
不过还是对这个项目发起人老哥还是赞一个， 只是那个配置项貌似是不存在的吧

**Comment by meteorlxy** [comment]
还在内测阶段，鹅厂内部有的

**Comment by meteorlxy** [comment]
我更新一下文档，标注一下吧

**Comment by darkfe** [comment]
> 我更新一下文档，标注一下吧

大佬知道什么时候开放，或者如何申请内测资格么，等这个功能很久了

**Comment by meteorlxy** [comment]
@darkfe 不太清楚哈，可以尝试问一下客服？

**Comment by arleyGuoLei** [comment]
`企业微信 - 机器人配置 - 接收消息配置 - Token / EncodingAESKey`

如果企业有这个内测权限，这个的具体位置能给截图下吗？是企业微信管理员才有这个入口？还是机器人创建者就可以看到？

**Comment by meteorlxy** [comment]
@arley 

机器人创建者就可以看到

![image](https://user-images.githubusercontent.com/18205362/135199235-ec85dc88-670f-4220-8ba1-7d5bd82a4c2f.png)
